### PR TITLE
cyan doesn't show up. :(

### PR DESCRIPTION
**Pull request by RikerW**

### CODE REVIEW

**Comment by quartata** [comment]
The color was changed to cyan because the background changes to blue at night; oasis tiles would be invisible. If you have a better color suggestion I'm all ears; it just can't be blue.

**Comment by newbiedoodle** [comment]
Add a screenshot of cyan not showing up, please.

**Comment by RikerW** [comment]
It shows up, but it hard to see. 
screen shot 2016-04-06 at 6 24 08 pm

**Comment by newbiedoodle** [comment]
Alright, I'm closing this because... well, you already fixed this issue with the dual rendering thing.

**Pull request closed without merging**
